name: Terraform CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend_node/infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create backend.tf
        run: |
          cat > backend.tf << EOF
          terraform {
            backend "remote" {
              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"

              workspaces {
                name = "${{ secrets.TF_CLOUD_WORKSPACE }}"
              }
            }
          }
          EOF

      - name: Terraform Init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_CLOUD_WORKSPACE: ${{ secrets.TF_CLOUD_WORKSPACE }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
