name: Terraform CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend_node/infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Export Secrets
        run: |
          echo "TF_ORG=${{ secrets.TF_CLOUD_ORGANIZATION }}" >> $GITHUB_ENV
          echo "TF_WS=${{ secrets.TF_CLOUD_WORKSPACE }}" >> $GITHUB_ENV

      - name: Create backend.tf
        run: |
          cat > ./Backend_node/infra/backend.tf << EOF
          terraform {
            backend "remote" {
              hostname     = "app.terraform.io"
              organization = "$TF_ORG"

              workspaces {
                name = "$TF_WS"
              }
            }
          }
          EOF

      - name: Configure Terraform Cloud credentials
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TF_TOKEN_app_terraform_io }}"
              }
            }
          }
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Cleanup backend.tf
        run: rm -f ./Backend_node/infra/backend.tf
